import {
  BatteryCharging,
  ChartNoAxesCombined,
  CreditCard,
  KeyRound,
  LayoutDashboard,
  LockKeyhole,
  MapPin,
  PlugZap,
  RadioTower,
  ScrollText,
  Settings,
  ShieldCheck,
  Smartphone,
  Timer,
  TriangleAlert,
  Users,
  Waves,
} from "lucide-react";

import type { AdminNavigationItem } from "@/types/navigation";

export const adminNavigation: AdminNavigationItem[] = [
  { title: "Overview", href: "/admin", icon: LayoutDashboard },
  { title: "Stations", href: "/admin/stations", icon: MapPin },
  { title: "Devices", href: "/admin/devices", icon: BatteryCharging },
  { title: "Credentials", href: "/admin/device-credentials", icon: KeyRound },
  { title: "Lockers", href: "/admin/lockers", icon: LockKeyhole },
  { title: "Charging Ports", href: "/admin/charging-ports", icon: PlugZap },
  { title: "Commands", href: "/admin/device-commands", icon: RadioTower },
  { title: "Events", href: "/admin/device-events", icon: Timer },
  { title: "Telemetry", href: "/admin/device-telemetry", icon: Waves },
  { title: "Payments", href: "/admin/payments", icon: CreditCard },
  { title: "Mobile APIs", href: "/admin/mobile", icon: Smartphone },
  { title: "Users", href: "/admin/users", icon: Users },
  { title: "Roles", href: "/admin/roles", icon: ShieldCheck },
  { title: "Permissions", href: "/admin/permissions", icon: ShieldCheck },
  { title: "Assignments", href: "/admin/role-assignments", icon: Users },
  { title: "Audit Logs", href: "/admin/audit-logs", icon: ScrollText },
  { title: "Alerts", href: null, icon: TriangleAlert, disabled: true },
  { title: "Reports", href: null, icon: ChartNoAxesCombined, disabled: true },
  { title: "Settings", href: null, icon: Settings, disabled: true },
];
